version: '3'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
   
    #ended up putting this in the .env file
    # environment:
    #   - DUCKDNS_TOKEN=edd9235c-f2f5-49bf-a2a4-795bfde5fac8

      # - CF_API_EMAIL=user@example.com
      # - CF_DNS_API_TOKEN=YOU_API_TOKEN
      # - CF_API_KEY=YOU_API_KEY
      # be sure to use the correct one depending on if you are using a token or key
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/ubuntu/docker-data/traefik/data/traefik.yml:/traefik.yml:ro
      - /home/ubuntu/docker-data/traefik/data/acme.json:/acme.json
      - /home/ubuntu/docker-data/traefik/data/configurations:/configurations

      # - /home/username/traefik/data/traefik.yml:/traefik.yml:ro
      # - /home/username/traefik/data/acme.json:/acme.json
      # - /home/username/traefik/data/config.yml:/config.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.papermario.duckdns.org`)"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.http.routers.traefik-secure.middlewares=user-auth@file"

      # - "traefik.http.routers.traefik-secure.tls.certresolver=duckdns"
      # - "traefik.http.routers.traefik-secure.tls=true"
      # - "traefik.http.routers.traefik.entrypoints=http"
      # - "traefik.http.routers.traefik.entrypoints=web"
      # - "traefik.http.routers.traefik.entrypoints=websecure"
      # - "traefik.http.routers.traefik.rule=Host(`traefik.papermario.duckdns.org`)"
      # - "traefik.http.middlewares.traefik-auth.basicauth.users=dax:$$apr1$$frBuWDhf$$Ud3OwbJTwU5pSLwepbLR7."
      # - "traefik.http.routers.traefik.service=traefik"
      # - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      # - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      # - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      # - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      # - "traefik.http.routers.traefik-secure.entrypoints=https"
      # - "traefik.http.routers.traefik-secure.rule=Host(`traefik.papermario.duckdns.org`)"
      # - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      # - "traefik.http.routers.traefik-secure.tls=true"
      # - "traefik.http.routers.traefik-secure.tls.certresolver=http"
      # - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      # - "traefik.http.routers.traefik-secure.tls.certresolver=duckdns"
      # - "traefik.http.routers.traefik-secure.tls.domains[0].main=local.example.com"
      # - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.local.example.com"
      # - "traefik.http.routers.traefik-secure.service=api@internal"

####################################################################################################

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/ubuntu/docker-data/portainer:/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.portainer-secure.entrypoints=websecure"
      - "traefik.http.routers.portainer-secure.rule=Host(`portainer.papermario.duckdns.org`)"
      - "traefik.http.routers.portainer-secure.service=portainer-service"
      - "traefik.http.services.portainer-service.loadbalancer.server.port=9000"

####################################################################################################

  headscale:
    image: headscale/headscale:latest
    container_name: headscale
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    # ports:
    #   - 27986:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/ubuntu/docker-data/headscale/config:/etc/headscale
      - /home/ubuntu/docker-data/headscale/data:/var/lib/headscale
    command: headscale serve
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.headscale-secure.entrypoints=websecure"
      - "traefik.http.routers.headscale-secure.rule=Host(`headscale.papermario.duckdns.org`)"
      - "traefik.http.routers.headscale-secure.service=headscale-service"
      - "traefik.http.services.headscale-service.loadbalancer.server.port=8080"

####################################################################################################

  healthchecks:
    # image: lscr.io/linuxserver/healthchecks
    image: linuxserver/healthchecks:latest
    container_name: healthchecks
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/ubuntu/docker-data/healthchecks:/config
    environment:
      - PUID=1000
      - PGID=100
      - SUPERUSER_EMAIL=kolinksmith@gmail.com
      - SUPERUSER_PASSWORD=nilok3
      - SITE_ROOT=http://localhost:8000
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.healthchecks-secure.entrypoints=websecure"
      - "traefik.http.routers.healthchecks-secure.rule=Host(`healthchecks.papermario.duckdns.org`)"
      - "traefik.http.routers.healthchecks-secure.service=healthchecks-service"
      - "traefik.http.services.healthchecks-service.loadbalancer.server.port=8000"

####################################################################################################

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    depends_on:
      - traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - APP_NAME="Gitea"
      - USER_UID=1000
      - USER_GID=1000
      - USER=git
      - RUN_MODE=prod
      - DOMAIN=gitea.papermario.duckdns.org
      - SSH_DOMAIN=gitea.papermario.duckdns.org
      - HTTP_PORT=3000
      - ROOT_URL=https://gitea.papermario.duckdns.org
      - SSH_PORT=222
      - SSH_LISTEN_PORT=22
      - DB_TYPE=sqlite3
      - GITEA__cache__ENABLED=true
      - GITEA__cache__ADAPTER=redis
      - GITEA__cache__HOST=redis://gitea-cache:6379/0?pool_size=100&idle_timeout=180s
      - GITEA__cache__ITEM_TTL=24h
    networks:
      - proxy
    volumes:
      - /home/ubuntu/docker-data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "222:22"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.gitea-secure.entrypoints=websecure"
      - "traefik.http.routers.gitea-secure.rule=Host(`gitea.papermario.duckdns.org`)"
      - "traefik.http.routers.gitea-secure.service=gitea-service"
      - "traefik.http.services.gitea-service.loadbalancer.server.port=3000"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"


  gitea-cache:
    container_name: gitea-cache
    image: redis:6-alpine
    restart: unless-stopped
    networks:
      - proxy
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 15s
      timeout: 3s
      retries: 30
    logging:
      driver: "json-file"
      options:
        max-size: "1m"


  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/ubuntu/docker-data/uptime-kuma:/data
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.uptime-kuma-secure.entrypoints=websecure"
      - "traefik.http.routers.uptime-kuma-secure.rule=Host(`uptime-kuma.papermario.duckdns.org`)"
      - "traefik.http.routers.uptime-kuma-secure.service=uptime-kuma-service"
      - "traefik.http.services.uptime-kuma-service.loadbalancer.server.port=3001"
      - "traefik.http.routers.uptime-kuma-secure.tls=true"

####################################################################################################

networks:
  proxy:
    external: true
